add_library(userA MODULE userA.cc) 
add_library(userB MODULE userB.cc)
add_library(user_store MODULE user_store.cc)
add_library(user_crashA MODULE user_crashA.cc)
add_library(user_crashB MODULE user_crashB.cc)

foreach (target IN ITEMS userA userB user_store user_crashA user_crashB)
	target_link_libraries(${target} PUBLIC user allocators)
	include_directories(${target} PUBLIC "${PROJECT_SOURCE_DIR}/include")
endforeach()
